// 阿里云区域列表
export const regionChoices: Record<string, string> = {
  'ap-northeast-1': 'ap-northeast-1 (日本东京)',
  'ap-northeast-2': 'ap-northeast-2 (韩国首尔)',
  'ap-southeast-1': 'ap-southeast-1 (新加坡)',
  'ap-southeast-3': 'ap-southeast-3 (马来西亚吉隆坡)',
  'ap-southeast-5': 'ap-southeast-5 (印度尼西亚雅加达)',
  'ap-southeast-6': 'ap-southeast-6 (菲律宾马尼拉)',
  'ap-southeast-7': 'ap-southeast-7 (泰国曼谷)',
  'cn-beijing': 'cn-beijing (北京)',
  'cn-chengdu': 'cn-chengdu (成都)',
  'cn-fuzhou': 'cn-fuzhou (福州)',
  'cn-guangzhou': 'cn-guangzhou (广州)',
  'cn-hangzhou': 'cn-hangzhou (杭州)',
  'cn-heyuan': 'cn-heyuan (河源)',
  'cn-huhehaote': 'cn-huhehaote (呼和浩特)',
  'cn-nanjing': 'cn-nanjing (南京)',
  'cn-qingdao': 'cn-qingdao (青岛)',
  'cn-shanghai': 'cn-shanghai (上海)',
  'cn-shenzhen': 'cn-shenzhen (深圳)',
  'cn-wuhan-lr': 'cn-wuhan-lr (武汉)',
  'cn-wulanchabu': 'cn-wulanchabu (乌兰察布)',
  'cn-zhangjiakou': 'cn-zhangjiakou (张家口)',
  'eu-central-1': 'eu-central-1 (德国法兰克福)',
  'eu-west-1': 'eu-west-1 (英国伦敦)',
  'me-east-1': 'me-east-1 (阿联酋迪拜)',
  'na-south-1': 'na-south-1 (墨西哥)',
  'us-east-1': 'us-east-1 (美国弗吉尼亚)',
  'us-west-1': 'us-west-1 (美国硅谷)',
}
